[build]
base = "./"
command = "cargo run"
publish = "./public"

[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[redirects]]
from = "https://unosmium.netlify.com/*"
to = "https://unosmium.org/:splat"
status = 301
force = true
